<?php
require_once __DIR__ . '/../../../../../../backend/php/core/Auth.php';
require_once __DIR__ . '/../../../../../../backend/php/shared/HelpCenter.php';
require_once __DIR__ . '/../../../../../../web/components/layout/dashboard_shell.php';
$user=require_role('owner_teacher');$id=(int)($_GET['id']??$_POST['id']??0);$article=help_article_by_id($id);$error=$message=null;
if(!$article){http_response_code(404);render_dashboard_shell($user,'Article Not Found','<div class="alert alert-danger">Article not found.</div>');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){try{help_save_article($_POST,$user);$article=help_article_by_id($id);$message='Article saved.';}catch(Throwable $e){$error=$e->getMessage();}}
ob_start();
?>
<div class="d-flex justify-content-between mb-4"><p class="text-muted">Edit help article.</p><a class="btn btn-outline-brand" href="/owner/help-center">Back</a></div><?php if($message):?><div class="alert alert-success"><?=htmlspecialchars($message,ENT_QUOTES,'UTF-8')?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></div><?php endif;?>
<form method="post" class="foundation-card"><input type="hidden" name="id" value="<?=$id?>"><div class="row g-3"><div class="col-md-8"><label class="form-label">Title</label><input class="form-control" name="title" value="<?=htmlspecialchars($article['title'],ENT_QUOTES,'UTF-8')?>" required></div><div class="col-md-4"><label class="form-label">Slug</label><input class="form-control ltr-safe" name="slug" value="<?=htmlspecialchars($article['slug'],ENT_QUOTES,'UTF-8')?>" required></div><div class="col-md-4"><label class="form-label">Role</label><select class="form-select" name="role"><?php foreach(['public','owner_teacher','student','parent','academy_partner','media_buyer'] as $r):?><option value="<?=$r?>" <?=$article['role']===$r?'selected':''?>><?=$r?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Category</label><input class="form-control" name="category" value="<?=htmlspecialchars($article['category'],ENT_QUOTES,'UTF-8')?>"></div><div class="col-md-2"><label class="form-label">Language</label><select class="form-select" name="language"><?php foreach(['both','en','ar'] as $l):?><option value="<?=$l?>" <?=$article['language']===$l?'selected':''?>><?=$l?></option><?php endforeach;?></select></div><div class="col-md-2"><label class="form-label">Status</label><select class="form-select" name="status"><?php foreach(['published','draft'] as $s):?><option value="<?=$s?>" <?=$article['status']===$s?'selected':''?>><?=$s?></option><?php endforeach;?></select></div><div class="col-md-8"><label class="form-label">Video URL optional</label><input class="form-control" name="video_url" value="<?=htmlspecialchars($article['video_url']??'',ENT_QUOTES,'UTF-8')?>"></div><div class="col-md-4"><label class="form-label">Sort order</label><input class="form-control" type="number" name="sort_order" value="<?=(int)$article['sort_order']?>"></div><div class="col-12"><label class="form-label">Content</label><textarea class="form-control" rows="12" name="content" required><?=htmlspecialchars($article['content'],ENT_QUOTES,'UTF-8')?></textarea></div><div class="col-12"><button class="btn btn-brand">Save Article</button></div></div></form>
<?php $content=ob_get_clean();render_dashboard_shell($user,'Edit Help Article',$content);