<?php
require_once __DIR__ . '/../../../../../backend/php/core/Auth.php';
require_once __DIR__ . '/../../../../../backend/php/shared/MaterialsLibrary.php';
require_once __DIR__ . '/../../../../../web/components/layout/dashboard_shell.php';
$user=require_role('owner_teacher');$error=null;$cats=material_categories();
if($_SERVER['REQUEST_METHOD']==='POST'){try{$id=material_create($_POST,$user,$_FILES);header('Location: /owner/materials/view?id='.$id);exit;}catch(Throwable $e){$error=$e->getMessage();}}
ob_start();
?>
<div class="d-flex justify-content-between mb-4"><p class="text-muted">Create or upload educational material. Uploaded HTML is handled safely.</p><a class="btn btn-outline-brand" href="/owner/materials">Back</a></div><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></div><?php endif;?>
<form method="post" enctype="multipart/form-data" class="foundation-card"><div class="row g-3"><div class="col-md-8"><label class="form-label">Title</label><input class="form-control" name="title" required></div><div class="col-md-4"><label class="form-label">Type</label><select class="form-select" name="material_type" required><?php foreach(['text_article','mixed_page','external_link','external_video','video_upload','audio_upload','pdf','powerpoint','document','image','html_file'] as $t):?><option value="<?=$t?>"><?=$t?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Category</label><select class="form-select" name="category_id"><option value="">None</option><?php foreach($cats as $c):?><option value="<?=(int)$c['id']?>"><?=htmlspecialchars($c['name'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></div><div class="col-md-2"><label class="form-label">Level</label><select class="form-select" name="level"><?php foreach(['not_set','A0','A1','A2','B1','B2','C1','C2','mixed'] as $l):?><option value="<?=$l?>"><?=$l?></option><?php endforeach;?></select></div><div class="col-md-3"><label class="form-label">Language</label><select class="form-select" name="material_language"><option value="both">Both</option><option value="ar">Arabic</option><option value="en">English</option></select></div><div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status"><option value="draft">Draft</option><option value="published">Published</option><option value="hidden">Hidden</option></select></div><div class="col-md-4"><label class="form-label">Estimated minutes</label><input class="form-control" name="estimated_study_minutes" type="number"></div><div class="col-md-8"><label class="form-label">External URL</label><input class="form-control" name="external_url" type="url"></div><div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description" rows="3"></textarea></div><div class="col-12"><label class="form-label">Text content</label><textarea class="form-control" name="text_content" rows="7"></textarea></div><div class="col-md-6"><label class="form-label">Upload file</label><input class="form-control" type="file" name="material_file"></div><div class="col-md-6"><label class="form-label">Tags</label><input class="form-control" name="tags"></div><div class="col-12"><div class="form-check"><input class="form-check-input" type="checkbox" name="allow_download" checked><label class="form-check-label">Allow download</label></div></div><div class="col-12"><label class="form-label">Teacher notes</label><textarea class="form-control" name="teacher_notes" rows="3"></textarea></div><div class="col-12"><button class="btn btn-brand">Create material</button></div></div></form>
<?php $content=ob_get_clean();render_dashboard_shell($user,'New Material',$content);