<?php
require_once __DIR__ . '/../../../../../../backend/php/core/Auth.php';
require_once __DIR__ . '/../../../../../../backend/php/shared/HelpCenter.php';
require_once __DIR__ . '/../../../../../../web/components/layout/dashboard_shell.php';
$user=require_role('owner_teacher');$error=null;
if($_SERVER['REQUEST_METHOD']==='POST'){try{$id=help_save_article($_POST,$user);header('Location: /owner/help-center/articles/edit?id='.$id);exit;}catch(Throwable $e){$error=$e->getMessage();}}
ob_start();
?>
<p class="text-muted">Create a help article for a specific role.</p><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></div><?php endif;?>
<form method="post" class="foundation-card"><div class="row g-3"><div class="col-md-8"><label class="form-label">Title</label><input class="form-control" name="title" required></div><div class="col-md-4"><label class="form-label">Slug</label><input class="form-control ltr-safe" name="slug" required></div><div class="col-md-4"><label class="form-label">Role</label><select class="form-select" name="role"><?php foreach(['public','owner_teacher','student','parent','academy_partner','media_buyer'] as $r):?><option value="<?=$r?>"><?=$r?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Category</label><input class="form-control" name="category" value="General"></div><div class="col-md-2"><label class="form-label">Language</label><select class="form-select" name="language"><option value="both">both</option><option value="en">en</option><option value="ar">ar</option></select></div><div class="col-md-2"><label class="form-label">Status</label><select class="form-select" name="status"><option value="published">published</option><option value="draft">draft</option></select></div><div class="col-md-8"><label class="form-label">Video URL optional</label><input class="form-control" name="video_url"></div><div class="col-md-4"><label class="form-label">Sort order</label><input class="form-control" type="number" name="sort_order" value="0"></div><div class="col-12"><label class="form-label">Content</label><textarea class="form-control" rows="12" name="content" required></textarea></div><div class="col-12"><button class="btn btn-brand">Save Article</button></div></div></form>
<?php $content=ob_get_clean();render_dashboard_shell($user,'New Help Article',$content);