<?php
require_once __DIR__ . '/../../../../../backend/php/core/Auth.php';
require_once __DIR__ . '/../../../../../backend/php/shared/MaterialsLibrary.php';
require_once __DIR__ . '/../../../../../web/components/layout/dashboard_shell.php';
$user=require_role('owner_teacher');$id=(int)($_GET['id']??0);$m=material_find($id);$error=$message=null;$cats=material_categories();
if(!$m){http_response_code(404);render_dashboard_shell($user,'Material Not Found','<div class="alert alert-danger">Material not found.</div>');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){try{material_update($id,$_POST,$user);$m=material_find($id);$message='Material updated.';}catch(Throwable $e){$error=$e->getMessage();}}
ob_start();
?>
<div class="d-flex justify-content-between mb-4"><p class="text-muted">Edit metadata, content, visibility, and download options.</p><a class="btn btn-outline-brand" href="/owner/materials/view?id=<?=$id?>">Preview</a></div><?php if($message):?><div class="alert alert-success"><?=htmlspecialchars($message,ENT_QUOTES,'UTF-8')?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></div><?php endif;?>
<form method="post" class="foundation-card"><div class="row g-3"><div class="col-md-8"><label class="form-label">Title</label><input class="form-control" name="title" value="<?=htmlspecialchars($m['title'],ENT_QUOTES,'UTF-8')?>" required></div><div class="col-md-4"><label class="form-label">Status</label><select class="form-select" name="status"><?php foreach(['draft','published','hidden','archived'] as $s):?><option value="<?=$s?>" <?=$m['status']===$s?'selected':''?>><?=$s?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Category</label><select class="form-select" name="category_id"><option value="">None</option><?php foreach($cats as $c):?><option value="<?=(int)$c['id']?>" <?=(int)$m['category_id']===(int)$c['id']?'selected':''?>><?=htmlspecialchars($c['name'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></div><div class="col-md-2"><label class="form-label">Level</label><select class="form-select" name="level"><?php foreach(['not_set','A0','A1','A2','B1','B2','C1','C2','mixed'] as $l):?><option value="<?=$l?>" <?=$m['level']===$l?'selected':''?>><?=$l?></option><?php endforeach;?></select></div><div class="col-md-3"><label class="form-label">Language</label><select class="form-select" name="material_language"><?php foreach(['both','ar','en'] as $l):?><option value="<?=$l?>" <?=$m['material_language']===$l?'selected':''?>><?=$l?></option><?php endforeach;?></select></div><div class="col-md-3"><label class="form-label">Minutes</label><input class="form-control" type="number" name="estimated_study_minutes" value="<?=htmlspecialchars((string)$m['estimated_study_minutes'],ENT_QUOTES,'UTF-8')?>"></div><div class="col-12"><label class="form-label">External URL</label><input class="form-control" type="url" name="external_url" value="<?=htmlspecialchars($m['external_url']??'',ENT_QUOTES,'UTF-8')?>"></div><div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description" rows="3"><?=htmlspecialchars($m['description']??'',ENT_QUOTES,'UTF-8')?></textarea></div><div class="col-12"><label class="form-label">Text content</label><textarea class="form-control" name="text_content" rows="7"><?=htmlspecialchars($m['text_content']??'',ENT_QUOTES,'UTF-8')?></textarea></div><div class="col-md-6"><label class="form-label">Tags</label><input class="form-control" name="tags" value="<?=htmlspecialchars($m['tags']??'',ENT_QUOTES,'UTF-8')?>"></div><div class="col-md-6"><div class="form-check mt-4"><input class="form-check-input" type="checkbox" name="allow_download" <?=$m['allow_download']?'checked':''?>><label class="form-check-label">Allow download</label></div></div><div class="col-12"><label class="form-label">Teacher notes</label><textarea class="form-control" name="teacher_notes" rows="3"><?=htmlspecialchars($m['teacher_notes']??'',ENT_QUOTES,'UTF-8')?></textarea></div><div class="col-12"><button class="btn btn-brand">Save changes</button></div></div></form>
<?php $content=ob_get_clean();render_dashboard_shell($user,'Edit Material',$content);