<?php
/**
 * /student/referrals
 * Student referrals. Own data only.
 */

require_once __DIR__ . '/../../../../backend/php/core/Auth.php';
require_once __DIR__ . '/../../../../backend/php/shared/StudentPortal.php';
require_once __DIR__ . '/../../../../web/components/layout/dashboard_shell.php';

$user = require_role('student');
$referrals = student_portal_referrals((int) $user['id']);

ob_start();
?>
<p class="text-muted">Invite friends and track referral status. Referral creation will be expanded in a later phase.</p>
<div class="alert alert-light border">Your referral code can be generated by the Owner or upcoming referral tools.</div>
<?php if (!$referrals): ?>
  <div class="alert alert-light border">No referrals yet.</div>
<?php else: ?>
  <div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Code</th><th>Referred email</th><th>Status</th><th>Reward</th></tr></thead><tbody>
  <?php foreach ($referrals as $referral): ?>
    <tr>
      <td><code><?= htmlspecialchars($referral['referral_code'], ENT_QUOTES, 'UTF-8') ?></code></td>
      <td><?= htmlspecialchars($referral['referred_email'] ?? '-', ENT_QUOTES, 'UTF-8') ?></td>
      <td><span class="badge text-bg-light border"><?= htmlspecialchars($referral['status'], ENT_QUOTES, 'UTF-8') ?></span></td>
      <td><?= htmlspecialchars((string) ($referral['reward_amount'] ?? '-'), ENT_QUOTES, 'UTF-8') ?></td>
    </tr>
  <?php endforeach; ?>
  </tbody></table></div>
<?php endif; ?>
<?php
$content = ob_get_clean();
render_dashboard_shell($user, 'Referrals', $content);
