<?php
/** /owner/scenarios/new */
require_once __DIR__ . '/../../../../../backend/php/core/Auth.php';
require_once __DIR__ . '/../../../../../backend/php/shared/LearningAssignments.php';
require_once __DIR__ . '/../../../../../web/components/layout/dashboard_shell.php';
$user=require_role('owner_teacher');$error=null;if($_SERVER['REQUEST_METHOD']==='POST'){try{$id=learning_create_scenario((int)$user['id'],$_POST);header('Location: /owner/scenarios/submissions?id='.$id);exit;}catch(Throwable $e){$error=$e->getMessage();}}
$students=learning_students_for_select();ob_start();
?>
<div class="d-flex justify-content-between mb-4"><p class="text-muted">Create a real-life speaking task.</p><a class="btn btn-outline-brand" href="/owner/scenarios">Back</a></div><?php if($error):?><div class="alert alert-danger"><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></div><?php endif;?>
<form method="post" class="foundation-card"><div class="row g-3"><div class="col-md-6"><label class="form-label">Student</label><select class="form-select" name="student_user_id" required><?php foreach($students as $s):?><option value="<?= (int)$s['id']?>"><?=htmlspecialchars($s['display_name'].' — '.$s['email'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></div><div class="col-md-3"><label class="form-label">Time limit seconds</label><input class="form-control" name="time_limit_seconds" value="60"></div><div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status"><option value="draft">draft</option><option value="published">published</option></select></div><div class="col-12"><label class="form-label">Title</label><input class="form-control" name="title" required></div><div class="col-12"><label class="form-label">Situation</label><textarea class="form-control" name="situation" rows="3" required></textarea></div><div class="col-12"><label class="form-label">Prompt</label><textarea class="form-control" name="prompt" rows="3" required></textarea></div><div class="col-12"><label class="form-label">Keywords</label><input class="form-control" name="keywords"></div><div class="col-12"><label class="form-label">Model answer optional</label><textarea class="form-control" name="model_answer" rows="4"></textarea></div><div class="col-12"><button class="btn btn-brand">Create scenario</button></div></div></form>
<?php $content=ob_get_clean();render_dashboard_shell($user,'Create Scenario',$content);